version: "3"

volumes:  
  postgres_data: {} 

services:  
  app:    
    build:      
      context: .      
      dockerfile: ./docker/app/dockerfile    
    depends_on:      
      - db    


  db:    
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/dockerfile    
    depends_on:      
      - app    
    ports:      
      - 80:80

  helpy:
    image: helpy/helpy
    restart: always
    volumes:
      - ./:/helpy/public
